/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ggggght_agent_VMTools */

#ifndef _Included_com_ggggght_agent_VMTools
#define _Included_com_ggggght_agent_VMTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ggggght_agent_VMTools
 * Method:    getInstances0
 * Signature: (Ljava/lang/Class;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ggggght_agent_VMTools_getInstances0
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
